package colruyt.rearulmgtdmnejb.util;

public class ExceptionMessageConstants {

	public static final String MESSAGE_DUPLICATE_RULESET = "MESSAGE_DUPLICATE_RULESET";
	public static final String MESSAGE_FromGreaterThanTo_ImportanceCode_VALIDATION = "MESSAGE_FromGreaterThanTo_ImportanceCode_VALIDATION";
	public static final String MESSAGE_Range_ImportanceCode_VALIDATION = "MESSAGE_Range_ImportanceCode_VALIDATION";
	public static final String MESSAGE_FromGreaterThanTo_Date_VALIDATION = "MESSAGE_FromGreaterThanTo_Date_VALIDATION";
	public static final String MESSAGE_FromLessThanCurrent_Date_VALIDATION = "MESSAGE_Range_Date_VALIDATION";
	public static final String MESSAGE_Invalid_NumberOfRecordings = "MESSAGE_Invalid_NumberOfRecordings";
	public static final String MESSAGE_THRESHOLD_VALUE_VALIDATION = "MESSAGE_THRESHOLD_VALUE_VALIDATION";
	public static final String MESSAGE_INVALID_REACTION_PERIOD = "MESSAGE_INVALID_REACTION_PERIOD";
	public static final String MESSAGE_FILTERING_RULE_VALIDATION = "MESSAGE_FILTERING_RULE_VALIDATION";
	public static final String MESSAGE_MANDATORY_FIELD_VALIDATION = "MESSAGE_MANDATORY_FIELD_VALIDATION";	
	public static final String MESSAGE_BENEFIT_TYPE_ABSENT = "MESSAGE_BENEFIT_TYPE_ABSENT";
	public static final String MESSAGE_SOURCE_ABSENT = "MESSAGE_SOURCE_ABSENT";
	public static final String MESSAGE_DURATION_ABSENT = "MESSAGE_DURATION_ABSENT";
	public static final String MESSAGE_BRAND_LAYER_ABSENT = "MESSAGE_BRAND_LAYER_ABSENT";
	public static final String MESSAGE_PRODUCT_HIERARCHY_SET_ABSENT = "MESSAGE_PRODUCT_HIERARCHY_SET_ABSENT";
	public static final String MESSAGE_IMPORTANCE_CODE_ABSENT = "MESSAGE_IMPORTANCE_CODE_ABSENT";
	public static final String MESSAGE_ASSORTMENT_NAME_ABSENT = "MESSAGE_ASSORTMENT_NAME_ABSENT";
	public static final String MESSAGE_RULE_NAME_ABSENT = "MESSAGE_RULE_NAME_ABSENT";
	public static final String MESSAGE_REACTION_RULE_ABSENT = "MESSAGE_REACTION_RULE_ABSENT";
	public static final String MESSAGE_REACTION_RULESET_ABSENT="MESSAGE_REACTION_RULESET_ABSENT";
	public static final String MESSAGE_RULETYPE_ABSENT = "MESSAGE_RULETYPE_ABSENT";
	public static final String MESSAGE_INVALID_CGCHAIN = "MESSAGE_INVALID_CGCHAIN";
	public static final String MESSAGE_INVALID_PCCHAIN = "MESSAGE_INVALID_PCCHAIN";
	public static final String MESSAGE_CATCHALL_VALIDTO = "MESSAGE_CATCHALL_VALIDTO";
	public static final String MESSAGE_CATCHALL_RULENAME = "MESSAGE_CATCHALL_RULENAME";
	public static final String MESSAGE_CATCHALL_PRICE_DURATAION_TYPE = "MESSAGE_CATCHALL_PRICE_DURATAION_TYPE";
	public static final String MESSAGE_CATCHALL_SOURCETYPE = "MESSAGE_CATCHALL_SOURCETYPE";
	public static final String MESSAGE_CATCHALL_ACTIONTYPE = "MESSAGE_CATCHALL_ACTIONTYPE";
	public static final String MESSAGE_CATCHALL_BENIFITTYPE = "MESSAGE_CATCHALL_BENIFITTYPE";
	public static final String MESSAGE_CATCHALL_IMPORTANCECODE = "MESSAGE_CATCHALL_IMPORTANCECODE";
	public static final String MESSAGE_CATCHALL_ASSORTMENTNAME = "MESSAGE_CATCHALL_ASSORTMENTNAME";
	public static final String MESSAGE_CATCHALL_BRAND = "MESSAGE_CATCHALL_BRAND";
	public static final String MESSAGE_REACTION_RULESETNAME_ABSENT="MESSAGE_REACTION_RULESET_NAME_ABSENT";

	
}
